/* ──────────────────────────────────────────────────────────────────
   Caastor v2, bilingual site copy (EN / ES)
   Verbatim from the Website Build Brief v1.0 (8 Jun 2026), Voice B.
   ────────────────────────────────────────────────────────────────── */
export const CONTENT = {
  en: {
    code: "EN",
    dir: "ltr",
    nav: { home: "Home", services: "Services", pricing: "Pricing", contact: "Contact", about: "About Us", faq: "FAQ", blog: "Blog" },
    login: "Login",
    headerCta: "Book a 30 minute demo",
    cta: {
      demo: "Book a 30 minute demo",
      pilot: "Start a risk free pilot",
      compare: "Compare plans",
      sales: "Talk to sales",
    },
    footer: {
      tagline: "Creativity without the bullsh*t.",
      newsletter: "Get design tips and the occasional bad pun.",
      newsletterCta: "Sign up",
      emailPh: "you@company.com",
      legal: "© 2026 Caastor. All rights reserved.",
      colNav: "Site",
      colLegal: "Legal",
      privacy: "Privacy",
      terms: "Terms",
    },
    home: {
      hero: {
        eyebrow: "Creativity without the bullsh*t.",
        h1a: "Your on demand design team,",
        h1serif: "senior work,",
        h1b: "shipped in 48 hours.",
        sub: "Unlimited design requests for one flat monthly fee, with briefs, feedback and brand assets all in one platform.",
        ctaPrimary: "Book a 30 minute demo",
        ctaSecondary: "See plans & pricing",
      },
      logos: {
        eyebrow: "Yes, those logos are real.",
        headline: "200+ brands trust Caastor with their design, from venture backed startups to Google, Deloitte Digital and the Dubai Chamber.",
        names: ["Google", "Deloitte Digital", "Dubai Chamber", "UOWD", "WCS", "Geoking", "Magnoos"],
      },
      intro: {
        eyebrow: "Positioning",
        headlineA: "Creative as a Service,",
        headlineSerif: "reimagined.",
        body: "Not an agency. Your on demand design team, senior work, one flat fee, shipped in 48 hours.",
        compare: {
          oldLabel: "The old way",
          newLabel: "With Caastor",
          old: [
            "Briefs lost in email threads",
            "Three to four week turnarounds",
            "A different junior each time",
            "Per project quotes and scope creep",
            "Assets scattered across chats",
          ],
          new: [
            "One platform for briefs, feedback and assets",
            "First drafts in 48 hours",
            "The same senior team, every time",
            "One flat monthly fee, cancel anytime",
            "Your whole Brand Library in one place",
          ],
        },
        cta: "See how it works ↓",
      },
      how: {
        eyebrow: "How it works",
        header: "From brief to shipped in three steps",
        steps: [
          { n: "01", title: "Send your brief", body: "Drop a request in the platform. As many as you like, queued and tracked." },
          { n: "02", title: "We design", body: "Your senior team gets to work. First drafts in ~48 hours." },
          { n: "03", title: "Review & ship", body: "Comment in the app, we refine, you ship. Every asset lives in your Brand Library." },
        ],
      },
      why: {
        eyebrow: "Why Caastor",
        header: "The system most teams don't have.",
        benefits: [
          { icon: "sparkles", title: "Quality that levels up your brand", body: "Senior designers, not the junior of the week, consistent across every channel thanks to your Brand Library." },
          { icon: "layers", title: "Zero operational friction", body: "One platform for briefs, feedback and assets. No more email chains, no more files lost in chat." },
          { icon: "activity", title: "Speed you can trust", body: "24 to 48 hour turnaround. Fast isn't sloppy, it's having the system most teams don't." },
        ],
      },
      services: {
        eyebrow: "What we design",
        header: "One subscription. Your whole design department.",
        cards: [
          { icon: "grid", tag: "Web", title: "Web design", body: "Websites that convert, not just look good." },
          { icon: "star", tag: "Brand", title: "Branding", body: "Identity that grows up with your business." },
          { icon: "message", tag: "Social", title: "Social design", body: "Scroll stopping content for every channel." },
        ],
        cta: "See everything we design →",
      },
      bundles: {
        eyebrow: "Bundles",
        header: "Don't buy services. Buy outcomes.",
        sub: "Curated bundles that combine the right work for a goal, run by one senior team on one subscription.",
        items: [
          {
            accent: "brand",
            tag: "Most popular",
            name: "Launch Kit",
            forWho: "Founders shipping a new brand or product",
            price: "From $1,200/mo",
            useCase: "Pick this when you have a launch date and need brand, site and social ready together.",
            desc: "Everything to launch a brand or product with a bang.",
            includes: ["Brand identity & logo", "Landing or marketing site", "Launch social set", "Pitch & sales deck"],
            excludes: ["Ongoing monthly content", "Paid ad campaign management", "Custom web development"],
          },
          {
            accent: "accent",
            tag: "",
            name: "Growth Engine",
            forWho: "Marketing teams running a constant pipeline",
            price: "From $1,600/mo",
            useCase: "Pick this when you ship across channels every week and need a steady creative flow.",
            desc: "A steady stream of creative that keeps the pipeline moving.",
            includes: ["Monthly social content", "Paid ad creative", "Email & lifecycle design", "Landing pages"],
            excludes: ["Full brand identity build", "Brand guidelines from scratch", "Native app UI design"],
          },
          {
            accent: "indigo",
            tag: "",
            name: "Brand System",
            forWho: "Scaling teams that need one source of truth",
            price: "From $2,000/mo",
            useCase: "Pick this when inconsistent design is slowing the team and you need a reusable foundation.",
            desc: "The identity and guidelines your whole team can build on.",
            includes: ["Logo & identity system", "Brand guidelines", "Templates & collateral", "Brand Library setup"],
            excludes: ["Weekly social posting", "Paid ad creative", "Website build and hosting"],
          },
        ],
        ctaPrimary: "Book a 30 minute demo",
        ctaSecondary: "Not sure? Talk to us",
      },
      testimonials: {
        eyebrow: "Testimonials",
        header: "Real brands. Real talk.",
        quotes: [
          { metric: "60%", metricLabel: "lower than in house cost", quote: "Like having an in house design team, without the overhead.", name: "Phil N.", role: "CEO, World Class Scholars", photo: "/assets/profile-photo-1.jpg" },
          { metric: "8 wks", metricLabel: "ahead of schedule", quote: "Launched our KSA dashboard two months ahead of schedule.", name: "Maher K.", role: "CEO, Geoking", photo: "/assets/profile-photo-2.jpg" },
          { metric: "48h", metricLabel: "to first drafts", quote: "No complex briefs needed, they just get it and deliver.", name: "Umer B.", role: "Founder, Grey Noise Gallery", photo: "/assets/profile-photo-3.jpg" },
          { metric: "2", metricLabel: "languages, native quality", quote: "Arabic and English, nailed from day one.", name: "Huda S.", role: "Founder, Bissan", photo: "/assets/profile-photo-4.jpg" },
        ],
      },
      faqTeaser: {
        eyebrow: "FAQ",
        header: "Good questions, straight answers.",
        cta: "See all FAQs →",
      },
      finalCta: {
        header: "See if Caastor fits, risk free.",
        body: "Start with a pilot or book a 30 minute demo. No annual contract. Pause or cancel anytime.",
        ctaPrimary: "Start a risk free pilot",
        ctaSecondary: "Book a demo",
      },
    },
    services: {
      eyebrow: "Services",
      h1: "One subscription. Your whole design department.",
      sub: "Every type of design your brand needs, delivered by senior designers in 24 to 48 hours, all from one platform.",
      items: [
        { icon: "star", tag: "Brand & identity", title: "Brand & identity", body: "Inconsistent, dated branding makes you look small. We build an identity system that scales with you and keeps every touchpoint on brand." },
        { icon: "grid", tag: "Web & UI/UX", title: "Web & UI/UX", body: "A pretty site that doesn't convert wastes traffic. We design pages and product screens around the action you want users to take." },
        { icon: "message", tag: "Social & content", title: "Social & content", body: "Generic posts get scrolled past. We turn your message into scroll stopping content sized and ready for every channel." },
        { icon: "layers", tag: "Graphic & layout", title: "Graphic & layout", body: "Cluttered decks and reports lose the room. We turn dense information into clean layouts that make you look like the leader you are." },
      ],
      cta: "Book a 30 minute demo",
    },
    pricing: {
      eyebrow: "Pricing",
      h1a: "Pick your pace.",
      h1serif: "Scale when you're ready.",
      sub: "Every plan includes unlimited requests, senior designers and your Brand Library. The only difference is speed and how much we run in parallel.",
      anchor: "60% faster and a fraction of the cost of an in house designer, salary, tools and management included.",
      currency: "$",
      per: "/mo",
      yearlyPer: "/yr",
      billing: { monthlyLabel: "Monthly", yearlyLabel: "Yearly", saveLabel: "2 months free" },
      popular: "Most popular",
      plans: [
        { sku: "Startup", price: "800", priceYearly: "8,000", best: "Solo founders and early teams testing the waters.", features: ["Unlimited requests", "Three to four day turnaround", "1 task at a time", "Social posts + basic web"], cta: "Start with Startup", variant: "outline" },
        { sku: "Growth", price: "1,600", priceYearly: "16,000", popular: true, best: "Brands shipping regularly across channels.", features: ["Unlimited requests", "Two day turnaround", "2 concurrent tasks", "Posts, ads, web & app assets"], cta: "Choose Growth", variant: "primary" },
        { sku: "Scale", price: "3,000", priceYearly: "30,000", best: "Fast moving teams with constant demand.", features: ["Unlimited requests", "One to two day turnaround", "3 concurrent tasks", "Advanced social + UI/UX"], cta: "Choose Scale", variant: "outline" },
        { sku: "Enterprise", price: "5,400", priceYearly: "54,000", best: "High volume brands that need it yesterday.", features: ["Unlimited requests", "24 to 48 hour express", "4+ concurrent tasks", "Custom across channels"], cta: "Talk to sales", variant: "outline" },
      ],
      helper: "Not sure which plan? Book a demo and we'll match you, no pressure.",
      risk: "No annual contract. No setup fees. Pause or cancel anytime, your Brand Library stays yours.",
      faqHeader: "Pricing questions",
      faqs: [
        { q: "What's a request?", a: "Any single design task, a post set, a landing page, a deck. If it's design, it's a request." },
        { q: "Concurrent tasks?", a: "How many requests we work on at once. More concurrency = we clear your queue faster." },
        { q: "Change plans?", a: "Anytime. Upgrade when you're busy, downgrade or pause when you're not." },
      ],
    },
    about: {
      eyebrow: "About us",
      h1a: "Creative as a Service,",
      h1serif: "without the agency baggage.",
      story: "Caastor started with a simple frustration: great brands kept losing time and money to slow, generic agencies. So we built the opposite, a senior design team you reach through one platform, that ships in 48 hours and treats you like a partner, not a ticket.",
      timeline: [
        { year: "2021", title: "The frustration", body: "After years inside agencies, we watched great brands lose time and money to slow, generic work." },
        { year: "2022", title: "Caastor is born", body: "We launched the opposite of an agency: a senior design team you reach through one platform." },
        { year: "2023", title: "48 hour turnaround", body: "We built the system and workflow that ships first drafts in 48 hours without cutting corners." },
        { year: "2024", title: "Bilingual by default", body: "Native Arabic and English design from day one opened the door to brands across the region." },
        { year: "2026", title: "200+ brands", body: "From venture backed startups to Google and Deloitte Digital, 200+ brands now trust us with their design." },
      ],
      missionLabel: "Our mission",
      mission: "We make your brand look like the business it's becoming.",
      valuesHeader: "What we stand for",
      values: [
        { title: "Senior & capable", body: "Real craft, not the junior of the week." },
        { title: "Playful, not gimmicky", body: "We have fun, you get results." },
        { title: "No drama, no hierarchy", body: "Same table, straight talk." },
      ],
      cta: "Book a 30 minute demo",
    },
    contact: {
      eyebrow: "Contact",
      h1: "Let's talk design.",
      sub: "Book a 30 minute demo and see the platform, the team and the turnaround for yourself.",
      fields: { name: "Name", email: "Work email", company: "Company", message: "What do you need?" },
      button: "Book my demo",
      micro: "We reply within one business day.",
      sentTitle: "You're booked, almost.",
      sentBody: "Thanks. We'll confirm a 30 minute slot within one business day.",
      asideTitle: "What to expect",
      asideItems: ["A 30 minute walkthrough, no slide deck.", "See the platform, the team and the real turnaround.", "We'll match you to the right plan. No pressure."],
    },
    faq: {
      eyebrow: "FAQ",
      h1: "Questions, handled.",
      sub: "Everything you need to know before you send your first brief.",
      items: [
        { q: "What is CaaS?", a: "Creative as a Service is a design subscription: unlimited requests, a senior team and one platform, for a flat monthly fee, no agency contracts." },
        { q: "How do I start?", a: "Book a 30 minute demo. Pick a plan, send your first brief, and get drafts within ~48 hours." },
        { q: "Turnaround?", a: "Most requests in 24 to 48 hours, depending on your plan and scope. Bigger projects are broken into fast milestones." },
        { q: "Change or cancel?", a: "Anytime. Upgrade, downgrade, pause or cancel, no permanence, no penalties." },
        { q: "Better than in house?", a: "A full senior team for a fraction of one salary, no recruiting, no tools to buy, no cover gaps." },
        { q: "Arabic design?", a: "Yes, native Arabic and English design from day one, no back and forth." },
        { q: "Is unlimited real?", a: "Yes. Request as much as you want; we work your queue one (or more) tasks at a time. No caps, no surprise fees." },
        { q: "Don't like it?", a: "We revise until it's right. Working from your Brand Library, we usually nail it early." },
      ],
      cta: "Book a 30 minute demo",
    },
  },

  es: {
    code: "ES",
    dir: "ltr",
    nav: { home: "Inicio", services: "Servicios", pricing: "Precios", contact: "Contacto", about: "Nosotros", faq: "FAQ", blog: "Blog" },
    login: "Acceder",
    headerCta: "Reserva una demo de 30 min",
    cta: {
      demo: "Reserva una demo de 30 min",
      pilot: "Empieza un piloto sin riesgo",
      compare: "Compara los planes",
      sales: "Habla con ventas",
    },
    footer: {
      tagline: "Creatividad sin humo.",
      newsletter: "Recibe tips de diseño y algún chiste malo.",
      newsletterCta: "Suscríbete",
      emailPh: "tu@empresa.com",
      legal: "© 2026 Caastor. Todos los derechos reservados.",
      colNav: "Sitio",
      colLegal: "Legal",
      privacy: "Privacidad",
      terms: "Términos",
    },
    home: {
      hero: {
        eyebrow: "Creatividad sin humo.",
        h1a: "Tu equipo de diseño a demanda,",
        h1serif: "nivel senior,",
        h1b: "entregado en 48 horas.",
        sub: "Peticiones de diseño ilimitadas por una tarifa plana al mes, con briefs, feedback y recursos de marca en una sola plataforma.",
        ctaPrimary: "Reserva una demo de 30 min",
        ctaSecondary: "Ver planes y precios",
      },
      logos: {
        eyebrow: "Sí, esos logos son de verdad.",
        headline: "Más de 200 marcas confían su diseño a Caastor, desde startups con inversión hasta Google, Deloitte Digital y la Cámara de Dubái.",
        names: ["Google", "Deloitte Digital", "Cámara de Dubái", "UOWD", "WCS", "Geoking", "Magnoos"],
      },
      intro: {
        eyebrow: "Posicionamiento",
        headlineA: "Creative as a Service,",
        headlineSerif: "reinventado.",
        body: "No una agencia. Tu equipo de diseño a demanda, nivel senior, tarifa plana, entregado en 48 horas.",
        compare: {
          oldLabel: "Lo de siempre",
          newLabel: "Con Caastor",
          old: [
            "Briefs perdidos en cadenas de email",
            "Plazos de 3 a 4 semanas",
            "Un junior distinto cada vez",
            "Presupuestos por proyecto",
            "Recursos dispersos en chats",
          ],
          new: [
            "Una plataforma para briefs, feedback y recursos",
            "Primeras propuestas en 48 horas",
            "El mismo equipo senior, siempre",
            "Una tarifa plana al mes, cancela cuando quieras",
            "Toda tu Brand Library en un sitio",
          ],
        },
        cta: "Mira cómo funciona ↓",
      },
      how: {
        eyebrow: "Cómo funciona",
        header: "Del brief a publicado, en tres pasos",
        steps: [
          { n: "01", title: "Envía tu brief", body: "Crea una petición en la plataforma. Las que quieras, en cola y con seguimiento." },
          { n: "02", title: "Diseñamos", body: "Tu equipo senior se pone manos a la obra. Primeras propuestas en ~48 horas." },
          { n: "03", title: "Revisa y publica", body: "Comenta en la app, afinamos y publicas. Cada recurso vive en tu Brand Library." },
        ],
      },
      why: {
        eyebrow: "Por qué Caastor",
        header: "El sistema que la mayoría no tiene.",
        benefits: [
          { icon: "sparkles", title: "Calidad que sube el nivel de tu marca", body: "Diseñadores senior, no el junior de turno, coherente en todos tus canales gracias a tu Brand Library." },
          { icon: "layers", title: "Cero fricción operativa", body: "Una plataforma para briefs, feedback y recursos. Se acabaron las cadenas de correos y los archivos perdidos en el chat." },
          { icon: "activity", title: "Velocidad de la que te puedes fiar", body: "Entregas en 24 a 48 horas. Rápido no es descuidado: es tener el sistema que la mayoría no tiene." },
        ],
      },
      services: {
        eyebrow: "Qué diseñamos",
        header: "Una suscripción. Todo tu departamento de diseño.",
        cards: [
          { icon: "grid", tag: "Web", title: "Diseño web", body: "Webs que convierten, no solo que se ven bien." },
          { icon: "star", tag: "Brand", title: "Branding", body: "Identidad que crece con tu negocio." },
          { icon: "message", tag: "Social", title: "Diseño social", body: "Contenido que para el scroll, para cada canal." },
        ],
        cta: "Mira todo lo que diseñamos →",
      },
      bundles: {
        eyebrow: "Packs",
        header: "No compres servicios. Compra resultados.",
        sub: "Packs que combinan el trabajo justo para un objetivo, con un solo equipo senior y una suscripción.",
        items: [
          {
            accent: "brand",
            tag: "Más popular",
            name: "Launch Kit",
            forWho: "Fundadores que lanzan marca o producto",
            price: "Desde 1.100 €/mes",
            useCase: "Elígelo cuando tienes fecha de lanzamiento y necesitas marca, web y social listos a la vez.",
            desc: "Todo para lanzar una marca o producto por todo lo alto.",
            includes: ["Identidad y logo", "Landing o web", "Set social de lanzamiento", "Deck de ventas"],
            excludes: ["Contenido mensual continuo", "Gestión de campañas de ads", "Desarrollo web a medida"],
          },
          {
            accent: "accent",
            tag: "",
            name: "Growth Engine",
            forWho: "Equipos de marketing con pipeline constante",
            price: "Desde 1.490 €/mes",
            useCase: "Elígelo cuando publicas en varios canales cada semana y necesitas un flujo creativo estable.",
            desc: "Un flujo constante de creatividad que mantiene el pipeline en marcha.",
            includes: ["Contenido social mensual", "Creatividades de ads", "Email y lifecycle", "Landing pages"],
            excludes: ["Construcción de identidad completa", "Guía de marca desde cero", "Diseño de UI de app nativa"],
          },
          {
            accent: "indigo",
            tag: "",
            name: "Brand System",
            forWho: "Equipos que escalan y necesitan una sola fuente",
            price: "Desde 1.890 €/mes",
            useCase: "Elígelo cuando el diseño incoherente frena al equipo y necesitas una base reutilizable.",
            desc: "La identidad y guías sobre las que todo tu equipo puede construir.",
            includes: ["Sistema de identidad", "Guía de marca", "Plantillas y colaterales", "Brand Library lista"],
            excludes: ["Publicación social semanal", "Creatividades de ads", "Construcción y hosting de web"],
          },
        ],
        ctaPrimary: "Reserva una demo de 30 min",
        ctaSecondary: "¿Dudas? Habla con nosotros",
      },
      testimonials: {
        eyebrow: "Testimonios",
        header: "Marcas reales. Sin postureo.",
        quotes: [
          { metric: "60%", metricLabel: "menos que un equipo interno", quote: "Es como tener un equipo de diseño interno, pero sin los costes fijos.", name: "Phil N.", role: "CEO, World Class Scholars", photo: "/assets/profile-photo-1.jpg" },
          { metric: "8 sem", metricLabel: "antes de lo previsto", quote: "Lanzamos nuestro dashboard para KSA dos meses antes de lo previsto.", name: "Maher K.", role: "CEO, Geoking", photo: "/assets/profile-photo-2.jpg" },
          { metric: "48h", metricLabel: "hasta las primeras propuestas", quote: "Sin briefs complicados, lo pillan y entregan.", name: "Umer B.", role: "Founder, Grey Noise Gallery", photo: "/assets/profile-photo-3.jpg" },
          { metric: "2", metricLabel: "idiomas, calidad nativa", quote: "Árabe e inglés, clavado desde el primer día.", name: "Huda S.", role: "Founder, Bissan", photo: "/assets/profile-photo-4.jpg" },
        ],
      },
      faqTeaser: {
        eyebrow: "FAQ",
        header: "Buenas preguntas, respuestas claras.",
        cta: "Ver todas las FAQ →",
      },
      finalCta: {
        header: "Comprueba si Caastor encaja, sin riesgo.",
        body: "Empieza con un piloto o reserva una demo de 30 minutos. Sin permanencia. Pausa o cancela cuando quieras.",
        ctaPrimary: "Empieza un piloto sin riesgo",
        ctaSecondary: "Reserva una demo",
      },
    },
    services: {
      eyebrow: "Servicios",
      h1: "Una suscripción. Todo tu departamento de diseño.",
      sub: "Cada tipo de diseño que tu marca necesita, de diseñadores senior, en 24 a 48 horas y desde una sola plataforma.",
      items: [
        { icon: "star", tag: "Marca e identidad", title: "Marca e identidad", body: "Una marca incoherente y anticuada te hace parecer pequeño. Creamos un sistema de identidad que escala contigo y mantiene cada punto de contacto en línea." },
        { icon: "grid", tag: "Web & UI/UX", title: "Web & UI/UX", body: "Una web bonita que no convierte malgasta el tráfico. Diseñamos páginas y pantallas de producto en torno a la acción que quieres que haga el usuario." },
        { icon: "message", tag: "Social y contenido", title: "Social y contenido", body: "Los posts genéricos se ignoran. Convertimos tu mensaje en contenido que para el scroll, con el tamaño justo para cada canal." },
        { icon: "layers", tag: "Gráfica y layout", title: "Gráfica y layout", body: "Las presentaciones recargadas pierden a la sala. Convertimos información densa en layouts limpios que te hacen parecer el líder que eres." },
      ],
      cta: "Reserva una demo de 30 min",
    },
    pricing: {
      eyebrow: "Precios",
      h1a: "Elige tu ritmo.",
      h1serif: "Escala cuando estés listo.",
      sub: "Todos los planes incluyen peticiones ilimitadas, diseñadores senior y tu Brand Library. La única diferencia es la velocidad y cuánto trabajamos en paralelo.",
      anchor: "Un 60% más rápido y una fracción del coste de un diseñador en plantilla en España, sueldo, herramientas y gestión incluidos.",
      currency: "€",
      per: "/mes",
      yearlyPer: "/año",
      vat: "IVA no incluido",
      billing: { monthlyLabel: "Mensual", yearlyLabel: "Anual", saveLabel: "2 meses gratis" },
      popular: "El más elegido",
      plans: [
        { sku: "Startup", price: "750", priceYearly: "7.500", best: "Fundadores en solitario y equipos que empiezan a probar.", features: ["Peticiones ilimitadas", "Entrega de tres a cuatro días", "1 tarea a la vez", "Posts sociales + web básica"], cta: "Empieza con Startup", variant: "outline" },
        { sku: "Growth", price: "1.490", priceYearly: "14.900", popular: true, best: "Marcas que publican con regularidad en varios canales.", features: ["Peticiones ilimitadas", "Entrega en dos días", "2 tareas simultáneas", "Posts, ads, web y assets de app"], cta: "Elige Growth", variant: "primary" },
        { sku: "Scale", price: "2.790", priceYearly: "27.900", best: "Equipos rápidos con demanda constante.", features: ["Peticiones ilimitadas", "Entrega de uno a dos días", "3 tareas simultáneas", "Social avanzado + UI/UX"], cta: "Elige Scale", variant: "outline" },
        { sku: "Enterprise", price: "4.990", priceYearly: "49.900", best: "Marcas de alto volumen que lo necesitan para ayer.", features: ["Peticiones ilimitadas", "Express 24 a 48 horas", "4+ tareas simultáneas", "A medida en todos los canales"], cta: "Habla con ventas", variant: "outline" },
      ],
      helper: "¿No sabes qué plan? Reserva una demo y te ayudamos a elegir, sin presión.",
      risk: "Sin permanencia. Sin coste de alta. Pausa o cancela cuando quieras, tu Brand Library sigue siendo tuya.",
      faqHeader: "Preguntas sobre precios",
      faqs: [
        { q: "¿Qué es una petición?", a: "Cualquier tarea de diseño: un set de posts, una landing, una presentación. Si es diseño, es una petición." },
        { q: "¿Tareas simultáneas?", a: "Cuántas peticiones trabajamos a la vez. Más simultáneas = vaciamos tu cola más rápido." },
        { q: "¿Cambiar de plan?", a: "Cuando quieras. Sube cuando tengas mucho, baja o pausa cuando no." },
      ],
    },
    about: {
      eyebrow: "Nosotros",
      h1a: "Creative as a Service,",
      h1serif: "sin el lastre de la agencia.",
      story: "Caastor nació de una frustración simple: grandes marcas perdiendo tiempo y dinero con agencias lentas y genéricas. Así que construimos lo contrario, un equipo de diseño senior al que accedes desde una plataforma, que entrega en 48 horas y te trata como socio, no como un ticket.",
      timeline: [
        { year: "2021", title: "La frustración", body: "Tras años dentro de agencias, vimos a grandes marcas perder tiempo y dinero con trabajo lento y genérico." },
        { year: "2022", title: "Nace Caastor", body: "Lanzamos lo contrario de una agencia: un equipo de diseño senior al que accedes desde una plataforma." },
        { year: "2023", title: "Entrega en 48 horas", body: "Construimos el sistema y el flujo que entrega primeras propuestas en 48 horas sin recortar calidad." },
        { year: "2024", title: "Bilingüe por defecto", body: "Diseño nativo en árabe e inglés desde el primer día nos abrió la puerta a marcas de toda la región." },
        { year: "2026", title: "Más de 200 marcas", body: "De startups con inversión a Google y Deloitte Digital, más de 200 marcas confían su diseño en nosotros." },
      ],
      missionLabel: "Nuestra misión",
      mission: "Hacemos que tu marca se vea como el negocio en el que se está convirtiendo.",
      valuesHeader: "Lo que defendemos",
      values: [
        { title: "Senior y capaz", body: "Oficio de verdad, no el junior de turno." },
        { title: "Con gracia, sin gimmicks", body: "Nos divertimos, tú tienes resultados." },
        { title: "Sin dramas, sin jerarquías", body: "Misma mesa, hablamos claro." },
      ],
      cta: "Reserva una demo de 30 min",
    },
    contact: {
      eyebrow: "Contacto",
      h1: "Hablemos de diseño.",
      sub: "Reserva una demo de 30 minutos y comprueba la plataforma, el equipo y los plazos por ti mismo.",
      fields: { name: "Nombre", email: "Email de trabajo", company: "Empresa", message: "¿Qué necesitas?" },
      button: "Reservar mi demo",
      micro: "Respondemos en un día laborable.",
      sentTitle: "Casi reservada.",
      sentBody: "Gracias. Te confirmamos un hueco de 30 minutos en un día laborable.",
      asideTitle: "Qué esperar",
      asideItems: ["Un recorrido de 30 minutos, sin presentación.", "Ves la plataforma, el equipo y los plazos reales.", "Te ayudamos a elegir el plan. Sin presión."],
    },
    faq: {
      eyebrow: "FAQ",
      h1: "Preguntas, resueltas.",
      sub: "Todo lo que necesitas saber antes de enviar tu primer brief.",
      items: [
        { q: "¿Qué es CaaS?", a: "Creative as a Service es una suscripción de diseño: peticiones ilimitadas, un equipo senior y una plataforma, por una tarifa plana al mes, sin contratos de agencia." },
        { q: "¿Cómo empiezo?", a: "Reserva una demo de 30 minutos. Elige un plan, envía tu primer brief y recibe propuestas en ~48 horas." },
        { q: "¿Plazos?", a: "La mayoría en 24 a 48 horas, según tu plan y alcance. Los proyectos grandes se dividen en hitos rápidos." },
        { q: "¿Cambiar o cancelar?", a: "Cuando quieras. Sube, baja, pausa o cancela, sin permanencia ni penalizaciones." },
        { q: "¿Mejor que en plantilla?", a: "Un equipo senior completo por una fracción de un sueldo, sin selección, sin herramientas que comprar, sin huecos de cobertura." },
        { q: "¿Diseño en árabe?", a: "Sí, diseño nativo en árabe e inglés desde el primer día, sin idas y venidas." },
        { q: "¿El ilimitado es real?", a: "Sí. Pide todo lo que necesites; trabajamos tu cola de una (o más) tarea a la vez. Sin topes ni costes sorpresa." },
        { q: "¿No te gusta?", a: "Lo revisamos hasta que esté bien. Al trabajar desde tu Brand Library, solemos acertar pronto." },
      ],
      cta: "Reserva una demo de 30 min",
    },
  },
};
